version: "3.9"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
